security:
    firewalls:
          secure_area:
            pattern: ^/
            
            #Gestion du Fos classique
            form_login:
              provider:               fos_userbundle
              csrf_provider:          form.csrf_provider
              login_path:             fos_user_security_login 
              #cambouille de fos
              check_path:             fos_user_security_check
              #Redirection 
              default_target_path:    /home 
              #Si erreur de log on ramène sur home
              failure_path: /home
             
              
             #gestion du cookie remenber me
            #remerber_me:
             # key:  %secret%
             # livetime: 300000
             # path: /
            #  domain: ~
        
            # OAuth provider
            oauth:
                #Le failure_path permet la création du compte si il n'existait pas avant donc ne pas modifier
                failure_path: /connection
                login_path: /connection
                check_path: /connection
                default_target_path: /home 
                provider: fos_userbundle
                resource_owners:
                    github:           "/login/check-github"
                    facebook:         "/login/check-facebook"                 
                    google:           "/login/check-google"
                    linkedin:         "/login/check-linkedin"
                # If you want to set it to your custom user provider you have to implement OAuthAwareUserProviderInterface.
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            anonymous:    true
            logout:
                path:           /logout
                #where to go after logout
                target:         /home  
                #fix the bug de deconnexion 
                #https://github.com/symfony/symfony/issues/5868
                invalidate_session: false           
               
         